version: "2.3"
services:
        db-postgres:
                image: postgres:12
                environment:                        
                        POSTGRES_PASSWORD: 123456
                ports:
                        - "5442:5432"
                networks:
                        - docker-dev-env
        pgadmin:
                image: dpage/pgadmin4
                environment:
                        PGADMIN_DEFAULT_EMAIL: admin@admin.com
                        PGADMIN_DEFAULT_PASSWORD: admin
                ports:
                        - "8000:80"
                networks:
                        - docker-dev-env
networks:
        docker-dev-env:
                driver: bridge
